# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stepModel <- function(state, r, spec, nevents) {
    .Call('_generalSEIR_stepModel', PACKAGE = 'generalSEIR', state, r, spec, nevents)
}

tauleap <- function(state, r, spec, nevents, tau) {
    .Call('_generalSEIR_tauleap', PACKAGE = 'generalSEIR', state, r, spec, nevents, tau)
}

getRates <- function(var, par, nevents) {
    .Call('_generalSEIR_getRates', PACKAGE = 'generalSEIR', var, par, nevents)
}

simulate1 <- function(state, par, spec, nevents, tmax, inc) {
    .Call('_generalSEIR_simulate1', PACKAGE = 'generalSEIR', state, par, spec, nevents, tmax, inc)
}

simFixed <- function(var, par, spec, nevents, tmax) {
    .Call('_generalSEIR_simFixed', PACKAGE = 'generalSEIR', var, par, spec, nevents, tmax)
}

stepModelVax <- function(state, r, spec, nevents) {
    .Call('_generalSEIR_stepModelVax', PACKAGE = 'generalSEIR', state, r, spec, nevents)
}

tauleapVax <- function(state, r, spec, nevents, tau) {
    .Call('_generalSEIR_tauleapVax', PACKAGE = 'generalSEIR', state, r, spec, nevents, tau)
}

getRatesVax <- function(var, par, nevents) {
    .Call('_generalSEIR_getRatesVax', PACKAGE = 'generalSEIR', var, par, nevents)
}

simulateVax <- function(state, par, spec, nevents, tmax, inc) {
    .Call('_generalSEIR_simulateVax', PACKAGE = 'generalSEIR', state, par, spec, nevents, tmax, inc)
}

